-- ==========================================
-- JIANGHU APP DATABASE SCHEMA
-- Generated by Gemini (Global Top-Tier Architect Persona)
-- ==========================================

-- 1. PROFILES (Extends auth.users)
-- Stores public user information like nickname and avatar.
create table public.profiles (
  id uuid not null references auth.users(id) on delete cascade primary key,
  nickname text,
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Public profiles are viewable by everyone.
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile." on public.profiles for update using (auth.uid() = id);

-- TRIGGER: Auto-create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, nickname, avatar_url)
  values (new.id, new.raw_user_meta_data->>'nickname', new.raw_user_meta_data->>'avatarUrl');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. LOCATIONS (Core Content)
-- Stores the detailed guide data for each location.
create table public.locations (
  id text primary key, -- Using text ID ('01', '02') to match mock data, but UUID is recommended for new entries
  title text not null,
  category text, -- 'SIGHTSEEING', 'TRANSPORT', etc.
  description text,
  tips text[], -- Array of strings
  transport text,
  image_url text,
  tags text[], -- Array of hashtags
  brief text, -- Short description for list view
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Everyone can read locations. Only admins (service role) can write ideally, but for now we allow authenticated if needed or just keep it read-only for users.
alter table public.locations enable row level security;
create policy "Locations are viewable by everyone." on public.locations for select using (true);


-- 3. LOCATION COMMENTS (User Interaction)
-- Raw storage for comments.
create table public.raw_location_comments (
  id uuid default gen_random_uuid() primary key,
  location_id text references public.locations(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null default auth.uid(),
  text text not null,
  rating integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Everyone can read comments. Authenticated users can post.
alter table public.raw_location_comments enable row level security;
create policy "Comments are viewable by everyone." on public.raw_location_comments for select using (true);
create policy "Authenticated users can insert comments." on public.raw_location_comments for insert with check (auth.role() = 'authenticated');
create policy "Users can update own comments." on public.raw_location_comments for update using (auth.uid() = user_id);

-- VIEW: location_comments
-- Joins profiles to provide the denormalized view expected by the frontend API.
create or replace view public.location_comments 
with (security_invoker = true)
as
select 
  c.id,
  c.location_id,
  c.text,
  c.rating,
  c.created_at,
  c.user_id,
  p.nickname as user_name,
  p.avatar_url as user_avatar
from public.raw_location_comments c
left join public.profiles p on c.user_id = p.id;

-- FUNCTION: Handle Insert into View
-- Allows the frontend to "insert" into the view, redirecting it to the raw table.
create or replace function public.insert_location_comment()
returns trigger as $$
begin
  insert into public.raw_location_comments (location_id, text, rating, user_id)
  values (new.location_id, new.text, new.rating, auth.uid());
  return new;
end;
$$ language plpgsql;

create trigger on_location_comment_insert
  instead of insert on public.location_comments
  for each row execute procedure public.insert_location_comment();


-- 4. POIs (Map Data)
-- Points of Interest for the OSM map feature.
create table public.pois (
  id bigint primary key, -- OSM ID usually
  lat double precision not null,
  lon double precision not null,
  tags jsonb, -- Flexible storage for OSM tags
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.pois enable row level security;
create policy "POIs are viewable by everyone." on public.pois for select using (true);


-- 5. POI REPORTS (User Feedback)
-- Issues reported by users regarding map points.
create table public.poi_reports (
  id uuid default gen_random_uuid() primary key,
  poi_id bigint, -- Can reference pois(id) or be loose if POI is missing
  description text,
  type text,
  user_id uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.poi_reports enable row level security;
create policy "Authenticated users can insert reports." on public.poi_reports for insert with check (auth.role() = 'authenticated');


-- ==========================================
-- SEED DATA (Optional - Run if you want initial data)
-- ==========================================

-- insert into public.locations (id, title, category, description, tips, transport, image_url, tags)
-- values 
-- ('01', 'HONGYA CAVE', 'SIGHTSEEING', 'A real-life Spirited Away bathhouse...', ARRAY['Best View: Qiansimen Bridge'], 'Metro Line 1 or 6', 'https://example.com/hongya.jpg', ARRAY['#CYBERPUNK', '#NIGHT']);
